apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentdevopscloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopscloud
  template:
    metadata:
      labels:
        app: devopscloud
    spec:
      containers:
        - name: appnodejs
          image: mauroslucios/node-web-app:1.0
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  selector:
    app: devopscloud
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000
  type: NodePort