version: "3.7"
services:
  app_web:
    image: mauroslucios/node-web-app:1.0
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/app
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    
  db:
    image: 'mongo'
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db

      