apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicasetdevopscloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopscloud
  template:
    metadata:
      labels:
        app: devopscloud
    spec:
      containers:
        - name: appnodejs
          image: mauroslucios/node-web-app:1.0
          ports:
          - containerPort: 3000