name: Continuos Integration

on:
  pull_request:
jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
      - name: run install, build
        run: |
          npm install
          npm run build